version: '3.7'
services:
  prod_server:
    build: ./prod_server
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./prod_server:/usr/src/app
    env_file:
      - .env
    environment:
      - APP_SETTINGS=config.DevelopmentConfig

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - ./frontend:/app/node_modules
     
    links:
      - "prod_server:prod_server"
    