version: '3.7'
services:
  prod_server:
    build: ./prod_server
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./prod_server:/usr/src/app
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - FLASK_APP=manage.py
      - FLASK_DEBUG=1

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - ./frontend:/app/node_modules
      # - ./frontend/src:/usr/src/app/src
      # - ./frontend/public:/usr/src/app/public
    links:
      - "prod_server:prod_server"
    