# Generated by Django 2.2.6 on 2019-10-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='layer',
            name='area',
            field=models.FloatField(default=0),
        ),
    ]
